### ISSUE TITLE
Add apache license to code

### ISSUE THREAD

**Issue by brockn** [SepidehAyani/KafkaProducer#2]
We should add the ASL 2 license to this repo. Place the notice file in the main src dir:

https://github.com/streamsets/datacollector/blob/master/LICENSE.txt

and add the header to the java source file:

https://github.com/streamsets/datacollector/blob/master/container/src/main/java/com/streamsets/datacollector/execution/runner/common/ProductionObserver.java

**Comment by SepidehAyani** [comment]
I think they are done, but I would kindly like to ask for your conformation please.

**Comment by brockn** [comment]
Looks good! Two minor issues:

The file ASL2.txt should be called NOTICE.txt. This is standard in open source.

I see the .java file contains "Copyright Streamsets..." You should remove this line.

**Comment by SepidehAyani** [comment]
Thanks for reviewing it, they fixed.

**Comment by brockn** [comment]
nit: the file should be named "NOTICE.txt" not "NOTICE.txt."

:)
