### ISSUE TITLE
Use cloudera deps

### ISSUE THREAD

**Issue by brockn** [SepidehAyani/KafkaProducer#3]
The code currently uses CDH 5.5.0 Hadoop and upstream, non Cloudera, Kafka. We should update the dependencies to use Cloudera kafka. This just means updating the version string to the latest non-snapshot here:

https://repository.cloudera.com/artifactory/cloudera-repos/org/apache/kafka/kafka-clients/

**Comment by SepidehAyani** [comment]
Brock I should add the updated Kafka dependencies to my pom.xml~Maven file, right? and I think the answer is yes ;-) add those non-snapshot from the link above

**Comment by brockn** [comment]
Correct, since you are using CDH you should also use Cloudera Kafka.

**Comment by SepidehAyani** [comment]
I already had some, but it was not complete. So on my pom.xml file there is a part for Kafka Dependencies, which from line No 37 to 223, I added all the dependencies which has been in that linked above, excluded the snapshot files.

**Comment by brockn** [comment]
Sorry for the misscomunicaiton, what I meant was that you should change the version from 0.9.0 to the latest cloudera version 0.8.2.0-kafka-1.4.

This blog post https://phdata.io/build-a-hadoop-distribution-like-hortonworks-cloudera/ contains more information on why we want to use a version of the components from a vendor not from Apache.

So too summarize, I would:
- Remove the deps added
- Change the Kafka version number
- Test
- Commit. Please try and use a descriptive commit message. I see the last one was "Updated pom.xml"

**Comment by SepidehAyani** [comment]
oh I see, no I am sorry for being misunderstood. Working on it...

**Comment by SepidehAyani** [comment]
it should be ok now, thanks

**Comment by brockn** [comment]
Looks good!
